// The committed catalogue snapshot — the site's source of product data.
//
// Generated by `npm run build:catalogue` from WooCommerce and committed, rather
// than fetched at request time. The reasoning is the same one obsolete.ts makes
// about Unleashed: the store answers in 1.5-2.5s per request and refuses bursts,
// the content changes when someone edits a product in WordPress, and paying for
// it on every cold render bought us nothing. It also decouples the shop from the
// WordPress install entirely, which matters at the domain cutover.
//
// This module is deliberately dumb: it holds no visibility rules. Every one of
// the four rules (brand SKU, foreign brand, WordPress-hidden, ERP-retired) still
// lives at its single chokepoint in woocommerce.ts and still runs at read time,
// so the snapshot cannot drift from what we actually serve.
import catalogueData from "@/data/catalogue.json";
import variationData from "@/data/variations.json";
import categoryData from "@/data/categories.json";
import type { WcProduct, WcVariation } from "@/lib/woocommerce";

export type CategoryTerm = {
  id: number;
  slug: string;
  name: string;
  count: number;
  parent: number;
  description: string;
};

// The JSON is a faithful WooCommerce mirror, so it satisfies these shapes by
// construction. Casting through `unknown` keeps TypeScript from inferring a
// 3.5MB literal type for every field of every product.
const PRODUCTS = (catalogueData as unknown as { products: WcProduct[] }).products;
const VARIATIONS = (variationData as unknown as { byProductId: Record<string, WcVariation[]> })
  .byProductId;
const TERMS = (categoryData as unknown as { terms: CategoryTerm[] }).terms;

export const catalogueSize = PRODUCTS.length;

// Products in the store's menu_order, the order the snapshot was fetched in.
export function allProducts(): WcProduct[] {
  return PRODUCTS;
}

const BY_SLUG = new Map(PRODUCTS.map((p) => [p.slug, p]));

export function productBySlug(slug: string): WcProduct | undefined {
  return BY_SLUG.get(slug);
}

export function variationsFor(productId: number): WcVariation[] {
  return VARIATIONS[String(productId)] ?? [];
}

export function categoryTerms(): CategoryTerm[] {
  return TERMS;
}

export function categoryChildren(parentId: number): CategoryTerm[] {
  return TERMS.filter((t) => t.parent === parentId);
}

export function categoryById(id: number): CategoryTerm | undefined {
  return TERMS.find((t) => t.id === id);
}

// WooCommerce's `category=` filter matches the term AND its descendants, so a
// product assigned only to a child term still shows on the parent's page. Seven
// products depend on this: filtering on the parent id alone silently dropped 2
// from Body Weight, 1 from Cardio and 4 from Equipment Storage.
const DESCENDANTS = new Map<number, Set<number>>();

function withDescendants(categoryId: number): Set<number> {
  const cached = DESCENDANTS.get(categoryId);
  if (cached) return cached;
  const byParent = new Map<number, number[]>();
  for (const t of TERMS) {
    const siblings = byParent.get(t.parent);
    if (siblings) siblings.push(t.id);
    else byParent.set(t.parent, [t.id]);
  }
  const out = new Set<number>([categoryId]);
  const stack = [categoryId];
  while (stack.length) {
    for (const child of byParent.get(stack.pop() as number) ?? []) {
      if (!out.has(child)) {
        out.add(child);
        stack.push(child);
      }
    }
  }
  DESCENDANTS.set(categoryId, out);
  return out;
}

export function productsInCategory(categoryId: number): WcProduct[] {
  const ids = withDescendants(categoryId);
  return PRODUCTS.filter((p) => (p.categories ?? []).some((c) => ids.has(c.id)));
}

// WordPress searches post_title, post_excerpt and post_content, WooCommerce adds
// the SKU, and terms are AND-ed. Reproduced here so the snapshot returns the
// same set the live store did, then ranked: SKU hit first, then name, so a
// search for a product's name leads with the product rather than whatever
// mentions it in a description.
function haystack(p: WcProduct): string {
  return [p.name, p.sku, p.short_description, p.description]
    .filter(Boolean)
    .join(" ")
    .toLowerCase()
    .replace(/<[^>]*>/g, " ");
}

const HAYSTACKS = new WeakMap<WcProduct, string>();

function cachedHaystack(p: WcProduct): string {
  let h = HAYSTACKS.get(p);
  if (h === undefined) {
    h = haystack(p);
    HAYSTACKS.set(p, h);
  }
  return h;
}

export function searchCatalogue(query: string): WcProduct[] {
  const tokens = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (!tokens.length) return [];
  const scored: { p: WcProduct; score: number; index: number }[] = [];
  PRODUCTS.forEach((p, index) => {
    const hay = cachedHaystack(p);
    if (!tokens.every((t) => hay.includes(t))) return;
    const name = p.name.toLowerCase();
    const sku = (p.sku ?? "").toLowerCase();
    let score = 0;
    if (sku && tokens.some((t) => sku === t)) score += 100;
    if (name.includes(tokens.join(" "))) score += 50;
    if (tokens.every((t) => name.includes(t))) score += 25;
    scored.push({ p, score, index });
  });
  // menu_order breaks ties, so equally-relevant products keep the store's order.
  scored.sort((a, b) => b.score - a.score || a.index - b.index);
  return scored.map((s) => s.p);
}

// SKU lookup, for pairing a "-GROUP" bundle to the variable product that holds
// the range's per-size variations. See lib/ranges.ts.
const BY_SKU = new Map(
  PRODUCTS.filter((p) => p.sku).map((p) => [p.sku!.trim().toUpperCase(), p])
);

export function productBySku(sku: string): WcProduct | undefined {
  return BY_SKU.get(sku.trim().toUpperCase());
}
