// Products the ERP has retired. The list is generated by
// `npm run build:obsolete` and committed, rather than fetched at request time:
// reading it live meant pulling Unleashed's whole catalogue including obsolete
// records (10 pages instead of 6, ~2.5s each, throttled) on every cold render.
// Re-run that script when the ERP retires a product; `npm run check:obsolete`
// reports drift.
//
// This module deliberately depends on nothing but data, so `woocommerce.ts` can
// import it and apply BOTH halves of the obsolete rule at one chokepoint.
import obsoleteSkus from "./obsolete-skus.json";
import { skuAliases } from "./unleashed-aliases";

const RETIRED = new Set(obsoleteSkus.codes.map((c) => c.toUpperCase()));

// The catalogue and the ERP use different code schemes for the same product
// (see `unleashed-aliases`), so a WooCommerce SKU has to be resolved the same
// way pricing resolves it, or a retired product slips through under its web SKU.
// An unknown SKU is NOT retired: plenty of products have no ERP match at all and
// must keep selling.
export function isRetiredSku(sku?: string): boolean {
  if (!sku) return false;
  const up = sku.trim().toUpperCase();
  if (RETIRED.has(up)) return true;
  const alias = skuAliases[up];
  return alias ? RETIRED.has(alias.toUpperCase()) : false;
}

export const retiredSkuCount = RETIRED.size;
