// Splits the products that cannot be freight quoted into three piles, because
// they are three different jobs for three different people.
//
//   npm run report:cartons
//     reports/carton-gaps.md
//     reports/carton-gaps.csv
//
// "33 products missing carton data" reads as a measuring exercise. It is not.
// Most of it is a unit error or a decision about how sets are sold, and the
// actual tape-measure list is small. Splitting it is the difference between
// someone starting on Monday and the whole thing sitting there.
import { writeFileSync } from "node:fs";
import { it } from "vitest";
import { allProducts, productsInCategory } from "@/lib/catalogue";
import { filterBrandSku, filterListable, type WcProduct } from "@/lib/woocommerce";

const MD = "reports/carton-gaps.md";
const CSV = "reports/carton-gaps.csv";

const num = (v: unknown) => {
  const n = parseFloat(String(v ?? "").replace(/[^0-9.]/g, ""));
  return Number.isFinite(n) && n > 0 ? n : 0;
};

type Row = { sku: string; name: string; kg: number; l: number; w: number; h: number };

// A carton side over 3m is not a carton, it is millimetres typed into a
// centimetre field. SCRWAR04 records 2440 x 610cm, which would be 24 metres.
const IMPLAUSIBLE_CM = 300;

const isImplausible = (r: Row) => Math.max(r.l, r.w, r.h) > IMPLAUSIBLE_CM;
const isIncomplete = (r: Row) => !r.kg || !r.l || !r.w || !r.h;

/**
 * A set has no single carton by definition: a 150kg plate set ships as several.
 * Detected by name AND by the -GROUP suffix, because "Competition Kettlebells"
 * gives nothing away in its name but MMKBPGC-GROUP does.
 */
const isSet = (r: Row) =>
  /\bset of\b|\bpair(s)?\b|\bpack\b|\bgroup\b/i.test(r.name) || /-GROUP$/i.test(r.sku);

const q = (s: unknown) => `"${String(s ?? "").replace(/"/g, '""')}"`;

function recorded(r: Row): string {
  const parts = [
    r.kg ? `${r.kg}kg` : null,
    r.l ? `L${r.l}` : null,
    r.w ? `W${r.w}` : null,
    r.h ? `H${r.h}` : null,
  ].filter(Boolean);
  return parts.length ? parts.join(" ") : "nothing";
}

/** Only offered where a value is implausible by exactly the usual factor. */
function suggestion(r: Row): string {
  if (!isImplausible(r)) return "";
  const fix = (v: number) => (v > IMPLAUSIBLE_CM ? `${Math.round(v / 10)}` : `${v || "?"}`);
  return `suspected ${fix(r.l)} x ${fix(r.w)} x ${fix(r.h)}cm, confirm`;
}

it("writes the carton gap worklist", () => {
  const clearance = new Set(productsInCategory(356).map((p) => p.id));
  const served = allProducts().filter(
    (p) => filterListable([p]).length > 0 && (clearance.has(p.id) || filterBrandSku([p]).length > 0)
  );

  const rows: Row[] = served.map((p: WcProduct) => ({
    sku: p.sku ?? "",
    name: p.name,
    kg: num(p.weight),
    l: num(p.dimensions?.length),
    w: num(p.dimensions?.width),
    h: num(p.dimensions?.height),
  }));

  const blocked = rows.filter((r) => isIncomplete(r) || isImplausible(r));

  // A set is a decision whatever state its data is in, so it is checked first.
  //
  // The remaining split is by WHO CAN FIX IT, not by how much data is present.
  // An implausible value is a typo somebody corrects at a keyboard. A missing
  // dimension needs the physical box, even when the weight is already recorded,
  // so those belong with the tape-measure pile rather than the desk pile.
  const sets = blocked.filter(isSet);
  const dataFix = blocked.filter((r) => !isSet(r) && isImplausible(r));
  const measure = blocked.filter((r) => !isSet(r) && !isImplausible(r));

  const table = (list: Row[], extra = false) =>
    list.length
      ? [
          `| SKU | Product | Recorded |${extra ? " Suggested |" : ""}`,
          `|---|---|---|${extra ? "---|" : ""}`,
          ...list.map(
            (r) => `| \`${r.sku}\` | ${r.name} | ${recorded(r)} |${extra ? ` ${suggestion(r) || "-"} |` : ""}`
          ),
        ].join("\n")
      : "_None._";

  const md = `# Carton data: what actually needs doing

Generated by \`npm run report:cartons\`. ${blocked.length} products cannot be
freight quoted online today. They are **three separate jobs**, not one.

| Pile | Count | Who | Effort |
|---|---|---|---|
| 1. Wrong units, live on the site now | ${dataFix.length} | Whoever edits WordPress | Minutes. Do these first. |
| 2. Sets and multi-packs | ${sets.length} | Commercial decision | A decision, not a task. |
| 3. Genuinely unmeasured | ${measure.length} | Someone with a tape measure | The only physical work. |

---

## Pile 1: wrong units, ${dataFix.length} products

These have data and it is wrong: recorded in millimetres inside a centimetre
field, so a side reads as tens of metres. \`SCRWAR04\` currently says its carton is
24 metres long.

**Correct these first regardless of anything else**, because the wrong figure is
on the live product page today and the support agent will read it out. The fix is
a keyboard job.

Note the \`?\` in the suggested column: three of these are also missing a height,
so they need one measurement on top of the correction. That does not change the
priority. A wrong number on the site is worse than a missing one.

${table(dataFix, true)}

Suggested values are the recorded figure divided by ten. **Confirm one against a
physical item before applying the rest**, in case the error is not uniform.

---

## Pile 2: sets and multi-packs, ${sets.length} products

A "Set of 10, 150kg" has no single carton because it ships as several. No
measurement makes these quotable as one parcel. Somebody has to decide:

- give each set a nominal consignment built from its component cartons, or
- exclude sets from online freight and send them to a manual quote, which is
  what happens today by accident rather than by choice.

${table(sets)}

---

## Pile 3: measure these, ${measure.length} products

The actual tape-measure list, and it is short. Mostly small accessories, so
measuring them likely makes them parcel-shippable rather than pallet freight,
which is the cheapest freight we have.

Some already have a weight recorded and only need dimensions. They are still
here rather than in pile 1, because you cannot type a dimension you have not
measured. The Recorded column shows what is already known.

Record the **shipping carton** in centimetres and gross weight in kilograms, not
the product's own size.

${table(measure)}

---

## What this is not

The spreadsheet \`260812-Missing-ProductData.xlsx\` does **not** cover any of
these. Its 73 rows are products with no buy price or supplier, which is a margin
problem, and its 6 CBM rows are volume only. Checked: zero overlap with any pile
above. Worth acting on, separately.
`;

  writeFileSync(MD, md);
  writeFileSync(
    CSV,
    [
      "pile,sku,product,recorded_kg,recorded_l_cm,recorded_w_cm,recorded_h_cm,action",
      ...dataFix.map((r) => ["1-units", q(r.sku), q(r.name), r.kg, r.l, r.w, r.h, q(suggestion(r) || "complete the record")].join(",")),
      ...sets.map((r) => ["2-set", q(r.sku), q(r.name), r.kg, r.l, r.w, r.h, q("decide how sets are quoted")].join(",")),
      ...measure.map((r) => ["3-measure", q(r.sku), q(r.name), r.kg, r.l, r.w, r.h, q("measure carton and gross weight")].join(",")),
    ].join("\n")
  );
});
