// The house style, checked against what Opinly is actually serving.
//
//   npm run check:content        writes reports/content-lint.md
//   CHECK=1 npm run check:content  exits non-zero on any `error` finding
//
// The CHECK split is the same one build:redirects / check:redirects uses: one
// script, two jobs. A human reads the report; CI reads the exit code.
//
// WHAT IT CAN SEE, AND WHAT IT CANNOT. @opinly/backend's client serves
// PUBLISHED posts only — there is no draft or scheduled access on it. So this
// catches a problem already on the site, which is worth having (the Four-Phase
// post is live with "fit-out" through its body as this is written) but is not
// the gate anyone actually wants.
//
// The gate wants the five posts sitting in `scheduled_review`, before they
// publish. Those are reachable through Opinly's management API, the one the
// dashboard and the MCP server use, on a different credential. When that key
// exists, `loadPosts` is the single function to change: the rules, the report
// and the CI wiring are all indifferent to where a post came from. That is why
// lib/content-rules.ts takes a plain object and does no fetching.
//
// IT FETCHES DIRECTLY rather than through lib/opinly-content's getOpinly(),
// for the same reason clearance-gaps.report.ts bypasses getUnleashedMap():
// that client wraps fetch in next/cache tags, which do nothing useful outside
// a Next request. Same API, plain fetch.
//
// Read-only. It measures; it changes nothing.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { it } from "vitest";
import { createOpinlyClient, type ContentNode } from "@opinly/backend";
import { lintPost, type Finding, type LintablePost } from "@/lib/content-rules";

const OUT = "reports/content-lint.md";
const CHECK = process.env.CHECK === "1";

/**
 * Environment first, `.env.local` second.
 *
 * The other report scripts read `.env.local` and nothing else, which is right
 * for a thing only ever run by hand. This one also runs in CI, where that file
 * does not exist and the key arrives as a repository secret.
 */
function env(name: string): string | undefined {
  if (process.env[name]) return process.env[name];
  if (!existsSync(".env.local")) return undefined;
  for (const line of readFileSync(".env.local", "utf8").split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m && m[1] === name) return m[2].replace(/^["']|["']$/g, "");
  }
  return undefined;
}

/** Opinly stores bodies as a node tree; the rules want words. */
function textOf(node: ContentNode | undefined): string {
  if (!node) return "";
  const here = node.text ?? "";
  const below = (node.content ?? []).map(textOf).join(" ");
  return [here, below].filter(Boolean).join(" ");
}

/**
 * Every published post, as the rules want them.
 *
 * THE SWAP POINT. Replace this one function with a management-API read and the
 * linter covers drafts and scheduled posts without any other change.
 */
async function loadPosts(apiKey: string): Promise<LintablePost[]> {
  const client = createOpinlyClient({ apiKey, fetch });

  const slugs: string[] = [];
  let cursor: string | undefined;
  do {
    const page = await client.posts({ limit: 50, cursor });
    slugs.push(...page.data.map((p) => p.slug));
    cursor = page.next_cursor ?? undefined;
  } while (cursor);

  const posts: LintablePost[] = [];
  for (const slug of slugs) {
    const full = await client.post(slug);
    if (!full) continue;
    posts.push({
      slug: full.slug,
      title: full.title,
      metaTitle: full.metaTitle,
      description: full.metaDescription ?? full.description,
      content: textOf(full.content),
      image: { alt: full.titleFile?.altText, title: full.titleFile?.title },
    });
  }
  return posts;
}

function render(results: { post: LintablePost; findings: Finding[] }[]): string {
  const all = results.flatMap((r) => r.findings);
  const errors = all.filter((f) => f.severity === "error");
  const warns = all.filter((f) => f.severity === "warn");

  const lines: string[] = [
    "# Content lint",
    "",
    `Generated by \`npm run check:content\` against published Opinly posts.`,
    "",
    `${results.length} posts · **${errors.length} errors** · ${warns.length} warnings`,
    "",
    "`error` means the rule cannot be wrong. `warn` means a human has to look —",
    "an unapproved figure may be perfectly well sourced, and the linter cannot tell.",
    "",
  ];

  if (!all.length) {
    lines.push("Nothing to report.", "");
    return lines.join("\n");
  }

  for (const { post, findings } of results) {
    if (!findings.length) continue;
    lines.push(`## ${post.title}`, "", `\`${post.slug}\``, "");
    lines.push("| | Rule | Field | Detail |", "|---|---|---|---|");
    for (const f of findings) {
      lines.push(
        `| ${f.severity === "error" ? "🔴" : "🟡"} | \`${f.rule}\` | \`${f.field}\` | ${f.detail} |`
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

it("content lint", { timeout: 120_000 }, async () => {
  const apiKey = env("OPINLY_API_KEY");

  // NOT A FAILURE. A fork, or a CI run without the secret, has no business
  // failing a build over a credential it was never given. Say so and stop.
  if (!apiKey) {
    console.log("OPINLY_API_KEY is not set — skipping. Set it to lint published posts.");
    return;
  }

  const posts = await loadPosts(apiKey);
  const results = posts.map((post) => ({ post, findings: lintPost(post) }));
  const errors = results.flatMap((r) => r.findings).filter((f) => f.severity === "error");
  const warns = results.flatMap((r) => r.findings).filter((f) => f.severity === "warn");

  const markdown = render(results);
  writeFileSync(OUT, markdown);
  console.log(`Wrote ${OUT}`);
  console.log(`  ${posts.length} posts, ${errors.length} errors, ${warns.length} warnings`);

  for (const { post, findings } of results) {
    for (const f of findings.filter((x) => x.severity === "error")) {
      console.log(`  ERROR  ${post.slug}  ${f.rule}  ${f.detail}`);
    }
  }

  if (CHECK && errors.length) {
    throw new Error(
      `${errors.length} content error(s) across ${results.filter((r) => r.findings.some((f) => f.severity === "error")).length} post(s) — see ${OUT}`
    );
  }
});
