// Does the mirror map say the same thing as the live one?
//
//   npm run check:mirror
//
// WHY THIS EXISTS. docs/erp-mirror-scope.md, order of work, step 2: "Compare its
// output against a live getUnleashedMap() and confirm they agree on every field
// before writing." The loader was written and run before that comparison existed.
// This is it, and it compares the built MAPS rather than the raw rows, because
// the map is what the site actually consumes — the GST multiplication, the
// /erp-bg image overrides and the obsolete filter all happen between the table
// and the thing a page reads, and a bug in any of them is invisible at row level.
//
// IT IS NOT A DEPLOY GATE and must not become one. It reads live Unleashed, so
// it costs ~16s and fails when the ERP is having a bad afternoon — the exact
// property that made check:catalogue a problem in the deploy chain. Run it
// before turning ERP_MIRROR_ENABLED on, and after a schema change.
//
// A DIFFERENCE IS NOT AUTOMATICALLY A FAULT. The mirror is a point-in-time copy:
// if somebody changed a price in Unleashed an hour ago, price rows will differ
// and that is the mirror being stale, which is what `synced_at` is for. What
// this is looking for is STRUCTURAL disagreement — a field that is always empty
// on one side, an axis swapped, GST applied twice, codes missing wholesale.
import { it, vi } from "vitest";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

// lib/unleashed wraps both map builds in Next's unstable_cache, which has no
// request context out here: it throws, the wrapper swallows it and returns {},
// and this report compares the mirror against an empty live map — which reads
// as "every code is only in the mirror" and is entirely an artefact. Same
// workaround copy-gaps.report.ts uses; the report wants one uncached read.
vi.mock("next/cache", () => ({
  unstable_cache: (fn: (...a: unknown[]) => unknown) => fn,
  revalidateTag: () => {},
  revalidatePath: () => {},
}));

// vitest.reports.config.mts does not load .env.local — `npm test` is offline and
// pure on purpose — so this reads it the way content.load.ts and
// erp-mirror.load.ts already do. Without it adminDb() sees no credentials and
// the mirror silently "does not answer", which looks like a finding and is not.
for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2].trim().replace(/^["']|["']$/g, "");
}

const OUT = "reports/erp-mirror-parity.md";

/** Fields compared exactly. `stock` is deliberately NOT among them — see below. */
const FIELDS = [
  "price",
  "name",
  "image",
  "brand",
  "group",
  "subgroup",
  "sellable",
  "guid",
  "widthCm",
  "heightCm",
  "depthCm",
  "weightKg",
] as const;

it(
  "mirror parity",
  async () => {
    process.env.HIDE_UNSHIPPABLE ??= "true";
    const { buildMapFromMirror, getUnleashedMapLive } = await import("@/lib/unleashed");

    const [mirror, live] = await Promise.all([buildMapFromMirror(), getUnleashedMapLive()]);

    const lines: string[] = [
      "# Mirror parity: `erp_products` against live Unleashed",
      "",
      "Generated by `npm run check:mirror`. Read-only, and **not** a deploy gate —",
      "it reads live Unleashed, so it is slow and fails when the ERP is unwell.",
      "",
    ];

    if (!mirror) {
      lines.push(
        "## The mirror did not answer",
        "",
        "`buildMapFromMirror()` returned null, which means one of: Supabase is not",
        "configured here, the table is below its row floor, or it is past the staleness",
        "ceiling. The reason is on stderr. **`ERP_MIRROR_ENABLED` would be falling back",
        "to live Unleashed**, so the site is correct — but the mirror is doing nothing.",
        "",
      );
      mkdirSync(dirname(OUT), { recursive: true });
      writeFileSync(OUT, lines.join("\n") + "\n");
      console.log(lines.slice(4).join("\n"));
      return;
    }

    const mCodes = new Set(Object.keys(mirror));
    const lCodes = new Set(Object.keys(live));
    const onlyMirror = [...mCodes].filter((c) => !lCodes.has(c));
    const onlyLive = [...lCodes].filter((c) => !mCodes.has(c));
    const shared = [...mCodes].filter((c) => lCodes.has(c));

    // Per-field disagreement across the codes both sides hold.
    const diffs: Record<string, { n: number; sample: string[] }> = {};
    for (const f of FIELDS) diffs[f] = { n: 0, sample: [] };

    for (const code of shared) {
      const a = mirror[code] as Record<string, unknown>;
      const b = live[code] as Record<string, unknown>;
      for (const f of FIELDS) {
        const x = a[f] ?? null;
        const y = b[f] ?? null;
        if (x === y) continue;
        // Floats: agree to the cent. A price rebuilt through GST on both sides
        // can differ in the last bit without meaning anything.
        if (typeof x === "number" && typeof y === "number" && Math.abs(x - y) < 0.005) continue;
        diffs[f].n++;
        if (diffs[f].sample.length < 5) diffs[f].sample.push(`${code}: mirror=${JSON.stringify(x)} live=${JSON.stringify(y)}`);
      }
    }

    const worst = Object.entries(diffs).filter(([, d]) => d.n > 0);

    lines.push(
      "## Coverage",
      "",
      "| | |",
      "|---|---|",
      `| Codes in the mirror | ${mCodes.size} |`,
      `| Codes live | ${lCodes.size} |`,
      `| In both | ${shared.length} |`,
      `| **Only in the mirror** | **${onlyMirror.length}** |`,
      `| **Only live** | **${onlyLive.length}** |`,
      "",
    );

    if (onlyMirror.length) {
      lines.push(
        "**Codes the mirror has and live does not** are the ones to look at first: the",
        "cache returning more than the source is how a retired product reaches a page.",
        "",
        ...onlyMirror.slice(0, 15).map((c) => `- \`${c}\``),
        ...(onlyMirror.length > 15 ? [`- …and ${onlyMirror.length - 15} more`] : []),
        "",
      );
    }
    if (onlyLive.length) {
      lines.push(
        "**Codes live has and the mirror does not** mean the mirror is behind — either",
        "products added since the last refresh, or the obsolete filter disagreeing.",
        "",
        ...onlyLive.slice(0, 15).map((c) => `- \`${c}\``),
        ...(onlyLive.length > 15 ? [`- …and ${onlyLive.length - 15} more`] : []),
        "",
      );
    }

    lines.push("## Fields", "", "| Field | Disagreements | of shared |", "|---|---|---|");
    for (const f of FIELDS) {
      const pct = shared.length ? ((diffs[f].n / shared.length) * 100).toFixed(1) : "0.0";
      lines.push(`| \`${f}\` | ${diffs[f].n} | ${pct}% |`);
    }
    lines.push("");

    if (worst.length) {
      lines.push("### Samples", "");
      for (const [f, d] of worst) {
        lines.push(`**\`${f}\`** — ${d.n}`, "", ...d.sample.map((s) => `- ${s}`), "");
      }
    }

    lines.push(
      "### Reading this",
      "",
      "**`stock` is not compared.** It changes every time something is picked, so it",
      "would disagree constantly and tell you nothing. It is also the field where being",
      "an hour behind matters least — the cart re-checks availability against live",
      "Unleashed at checkout, and the order path reprices from live too.",
      "",
      "**A scatter of `price` differences is staleness**, and expected: the mirror is a",
      "copy taken at `synced_at`. **A pattern is a bug** — every price out by exactly",
      "10% is GST applied twice or not at all; every `widthCm` matching live's",
      "`depthCm` is the axis order scrambled, which would misquote freight.",
      "",
      `_Last run: ${new Date().toISOString().slice(0, 16).replace("T", " ")}Z_`,
      "",
    );

    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, lines.join("\n") + "\n");

    console.log(
      `mirror ${mCodes.size} codes, live ${lCodes.size}, shared ${shared.length}\n` +
        `  only-mirror ${onlyMirror.length}, only-live ${onlyLive.length}\n` +
        (worst.length
          ? worst.map(([f, d]) => `  ${f}: ${d.n}`).join("\n")
          : "  every compared field agrees")
    );
  },
  180_000
);
