// How much of the shop can actually take a card, and how much still cannot.
//
//   npm run report:erponly
//     reports/erp-only-lines.md
//
// THE RULE THIS MEASURES. `canPay` in app/checkout/page.tsx requires every cart
// line to have `productId > 0` — a real WooCommerce product behind it — because
// a line with none cannot be re-priced by resolveOrderLines, which fails closed.
// Letting one reach the card form would fail the order AFTER the card was
// captured. So an ERP-only line goes to the quote flow no matter what the
// checkout mode is.
//
// WHY IT MATTERS MORE THAN IT SOUNDS. The catalogue is served from the ERP now
// (see erp-catalogue.ts) with WooCommerce kept only as the router for slugs and
// marketing copy. So "browsable" and "card-buyable" are two different sets, and
// nothing in the UI distinguishes them. Card checkout went live on 2026-09-06
// and this report says what share of the shop that actually opened.
//
// Read-only. It measures; it changes nothing.
import { createHmac } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { it } from "vitest";

const env = new Map<string, string>();
for (const line of readFileSync(".env.local", "utf8").split("\n")) {
  const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
  if (m) env.set(m[1], m[2].replace(/^["']|["']$/g, ""));
}
for (const [k, v] of env) if (!process.env[k]) process.env[k] = v;

const { allProducts, variationsFor } = await import("@/lib/catalogue");
const { isRetiredSku } = await import("@/lib/obsolete");

const OUT = "reports/erp-only-lines.md";
const out = (s: string) => process.stdout.write(`${s}\n`);

type ErpProduct = {
  ProductCode?: string;
  ProductDescription?: string;
  DefaultSellPrice?: number;
  ProductGroup?: { GroupName?: string };
  Obsolete?: boolean;
  IsSellable?: boolean;
};

const sign = (q: string) =>
  createHmac("sha256", process.env.UNLEASHED_API_KEY ?? "").update(q).digest("base64");

async function allErpProducts(): Promise<ErpProduct[]> {
  const items: ErpProduct[] = [];
  for (let page = 1; page <= 20; page++) {
    const q = `pageSize=200`;
    const res = await fetch(`https://api.unleashedsoftware.com/Products/${page}?${q}`, {
      headers: {
        "api-auth-id": process.env.UNLEASHED_API_ID ?? "",
        "api-auth-signature": sign(q),
        Accept: "application/json",
      },
    });
    if (!res.ok) break;
    const json = (await res.json()) as { Items?: ErpProduct[]; Pagination?: { NumberOfPages?: number } };
    const got = json.Items ?? [];
    items.push(...got);
    if (page >= (json.Pagination?.NumberOfPages ?? 1)) break;
  }
  return items;
}

it("measures what card checkout actually opened", async () => {
  // Every SKU the snapshot can put behind a cart line, INCLUDING variations —
  // a variation carries its own sku and its parent's productId, so it counts.
  const woo = new Set<string>();
  for (const p of allProducts()) {
    const sku = (p.sku ?? "").trim().toUpperCase();
    if (sku) woo.add(sku);
    for (const v of variationsFor(p.id)) {
      const vs = (v.sku ?? "").trim().toUpperCase();
      if (vs) woo.add(vs);
    }
  }

  const erp = await allErpProducts();
  // Sellable means: not retired, not flagged obsolete, and carrying a price.
  // A $0 code is "contact for pricing" and never reaches card checkout anyway.
  const sellable = erp.filter((p) => {
    const code = (p.ProductCode ?? "").trim();
    if (!code) return false;
    if (p.Obsolete) return false;
    if (isRetiredSku(code)) return false;
    return Number(p.DefaultSellPrice ?? 0) > 0;
  });

  const covered = sellable.filter((p) => woo.has((p.ProductCode ?? "").trim().toUpperCase()));
  const erpOnly = sellable.filter((p) => !woo.has((p.ProductCode ?? "").trim().toUpperCase()));

  const byGroup = new Map<string, { total: number; only: number }>();
  for (const p of sellable) {
    const g = p.ProductGroup?.GroupName ?? "(no group)";
    const row = byGroup.get(g) ?? { total: 0, only: 0 };
    row.total++;
    if (!woo.has((p.ProductCode ?? "").trim().toUpperCase())) row.only++;
    byGroup.set(g, row);
  }
  const groups = [...byGroup.entries()]
    .filter(([, r]) => r.total >= 3)
    .sort((a, b) => b[1].only / b[1].total - a[1].only / a[1].total || b[1].total - a[1].total);

  const pct = (n: number, d: number) => (d ? ((n / d) * 100).toFixed(0) : "0");

  const md = `# What card checkout actually opened

Generated by \`npm run report:erponly\`. Compares every sellable Unleashed product
code against the SKUs the committed WooCommerce snapshot can put behind a cart
line, variations included.

**The rule.** \`canPay\` requires \`productId > 0\` on every cart line. A line with no
WooCommerce product cannot be re-priced server-side by \`resolveOrderLines\`, which
fails closed, so it must never reach the card form — it would fail the order after
the card was captured. Those lines go to the quote flow regardless of checkout
mode.

## The split

| | | |
|---|---|---|
| Sellable ERP products | ${sellable.length} | |
| **Card-buyable** (a WooCommerce product exists) | **${covered.length}** | ${pct(covered.length, sellable.length)}% |
| **Quote-only** (ERP-only, no WooCommerce product) | **${erpOnly.length}** | ${pct(erpOnly.length, sellable.length)}% |

${erp.length} products read from Unleashed; the rest are retired, flagged obsolete,
or priced at $0 which is "contact for pricing" and never reaches card checkout.

⚠️ **This counts EVERY sellable ERP code, not only what the public site lists.**
The site is a brand allowlist, so REVL and other non-MasterKraft codes are in this
denominator but are not on masterkraft.com at all. The customer-facing quote-only
share is therefore **lower than the headline** above. Treat this as the ceiling on
the problem, not its size, and narrow it by brand before quoting it to anyone.

## Where the quote-only lines are

Groups with three or more sellable products, worst coverage first.

| group | sellable | quote-only | share |
|---|---|---|---|
${groups
  .map(([g, r]) => `| ${g} | ${r.total} | ${r.only} | ${pct(r.only, r.total)}% |`)
  .join("\n")}

## A sample of the quote-only lines

${
  erpOnly
    .slice(0, 40)
    .map(
      (p) =>
        `- \`${p.ProductCode}\` ${p.ProductDescription ?? ""} — $${Number(p.DefaultSellPrice ?? 0).toFixed(2)}`
    )
    .join("\n") || "_none_"
}

## What to do with this

If the quote-only share is small, nothing: those lines behave exactly as they did
before card checkout went live.

If it is large, the fix is not in the checkout. It is that these products have no
WooCommerce page, so \`resolveOrderLines\` cannot verify their price. Either give
them one, or extend server-side repricing to resolve an ERP-only line from the
ERP directly — at which point the \`productId > 0\` rule can be relaxed.
`;

  writeFileSync(OUT, md);
  out(`\nsellable ERP products: ${sellable.length}`);
  out(`card-buyable:  ${covered.length} (${pct(covered.length, sellable.length)}%)`);
  out(`quote-only:    ${erpOnly.length} (${pct(erpOnly.length, sellable.length)}%)`);
  out(`\nworst groups:`);
  for (const [g, r] of groups.slice(0, 10)) {
    out(`  ${g.padEnd(28)} ${String(r.only).padStart(3)}/${String(r.total).padEnd(3)} quote-only (${pct(r.only, r.total)}%)`);
  }
  out(`\nwritten to ${OUT}\n`);
}, 600_000);
